eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
      host: localhost
      port: 27017
      database: orderdb