server:
  port: 9094

spring:
  profiles:
    active: local
  application:
    name: ORDER-SERVICE
# configuration for mongoDB
  data:
    mongodb:
      repository:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true





